apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 25s

    scrape_configs:
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-cluster-kafka-exporter.kafka.svc.cluster.local:9404']

      # MUDANÇA CRUCIAL: Usar kubernetes_sd_configs para encontrar todos os pods
      - job_name: 'postgres'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['postgres']
        relabel_configs:
          # Filtra apenas pods que pertencem ao cluster postgres-core
          - source_labels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
            action: keep
            regex: postgres-core
          # Garante que ele tenta a porta de métricas 9187
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:9187
            target_label: __address__
          # Dá um nome bonito para cada instância no dashboard
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # Permissão para o Prometheus "listar" pods nos outros namespaces
      serviceAccountName: prometheus-sa
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.retention.time=7d"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config

---
# Permissões necessárias para o Service Discovery funcionar
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/metrics", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-server-role
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: monitoring