CREATE TABLE IF NOT EXISTS public.users
(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username character varying(50) NOT NULL,
  email character varying(255) NOT NULL,
  created_on timestamp NOT NULL DEFAULT now(),
  role character varying(50) NOT NULL DEFAULT 'user',
  last_login timestamp,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS public.accounts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    password text NOT NULL,
    email character varying(255) NOT NULL,
    created_on timestamp NOT NULL DEFAULT now(),
    last_login timestamp,
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_email_key UNIQUE (email),
    CONSTRAINT accounts_username_key UNIQUE (username),
    CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts(email);
CREATE INDEX IF NOT EXISTS idx_accounts_username ON accounts(username);
CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON accounts(user_id);

CREATE TABLE IF NOT EXISTS public.clients
(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  name character varying(255) NOT NULL,
  status character varying(50) NOT NULL,
  created_on timestamp NOT NULL DEFAULT now(),
  document character varying(255),
  documentType character varying(50),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES public.users (id)
      ON UPDATE CASCADE
      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_clients_user_id ON clients(user_id);

CREATE TABLE IF NOT EXISTS public.contacts
(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  client_id integer NOT NULL,
  type character varying(50) NOT NULL,
  "value" character varying(255) NOT NULL,
  created_on timestamp NOT NULL DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_unique_key UNIQUE ("value", type, client_id),
  CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES public.users (id)
      ON UPDATE CASCADE
      ON DELETE CASCADE,
  CONSTRAINT contacts_client_id_fkey FOREIGN KEY (client_id)
      REFERENCES public.clients (id)
      ON UPDATE CASCADE
      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_contacts_user_id ON contacts(user_id);
CREATE INDEX IF NOT EXISTS idx_contacts_client_id ON contacts(client_id);

CREATE TABLE IF NOT EXISTS public.addresses
(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  client_id integer NOT NULL,
  street character varying(255) NOT NULL,
  city character varying(100) NOT NULL,
  state character varying(100) NOT NULL,
  zip_code character varying(20) NOT NULL,
  country character varying(100) NOT NULL,
  created_on timestamp NOT NULL DEFAULT now(),
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id)
      REFERENCES public.users (id)
      ON UPDATE CASCADE
      ON DELETE CASCADE,
  CONSTRAINT addresses_client_id_fkey FOREIGN KEY (client_id)
      REFERENCES public.clients (id)
      ON UPDATE CASCADE
      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);
CREATE INDEX IF NOT EXISTS idx_addresses_client_id ON addresses(client_id);

INSERT INTO public.users (username, email, role) VALUES
('john_doe', 'john.doe@example.com', 'user');

INSERT INTO public.users (username, email, role) VALUES
('john_doe1', 'john.doe1@example.com', 'user');

INSERT INTO public.users (username, email, role) VALUES
('john_doe3', 'john.doe3@example.com', 'user');

INSERT INTO public.accounts (user_id, username, password, email) VALUES
(1, 'john_doe', 'password123', 'john.doe@example.com');

INSERT INTO public.accounts (user_id, username, password, email) VALUES
(2, 'john_doe1', 'password123', 'john.doe1@example.com');