http.port=8081
orders.host=orders-sapi.mulesoft.svc.cluster.local
orders.protocol=HTTP
orders.basePath=api/v{version}
orders.port=8081
items.host=items-sapi.mulesoft.svc.cluster.local
items.protocol=HTTP
items.basePath=api/v{version}
items.port=8081
kafka.brokers=kafka-cluster-kafka-bootstrap.kafka.svc:9092