#%RAML 1.0
title: Orders API
version: v1

traits: 
  pageable: !include traits/pageable.raml
  connection: !include traits/connection.raml

types: 
  request.post.orders: !include types/requests/post/orders.raml
  response.get.orders: !include types/responses/get/orders.raml
  requests.patch.payment: !include types/requests/patch/payment.raml
  requests.post.delivery: !include types/requests/post/delivery.raml

/{version}:
  /{id}:
    /delivery:
      post:
        is: [connection]
        description: Endpoint para iniciar a entrega de um pedido específico
        body:
          application/json:
            type: requests.post.delivery
        responses:
          200:
            description: Entrega iniciada com sucesso
          400:
            description: Requisição inválida, verifique os dados enviados
          404:
            description: Pedido não encontrado
          500:
            description: Erro interno do servidor, tente novamente mais tarde
    /payment:
      patch:
        is: [connection]
        description: Endpoint para atualizar o pagamento de um pedido específico
        body:
          application/json:
            type: requests.patch.payment
        responses:
          200:
            description: Pagamento atualizado com sucesso
          400:
            description: Requisição inválida, verifique os dados enviados
          404:
            description: Pedido não encontrado
          500:
            description: Erro interno do servidor, tente novamente mais tarde

  /:
    get:
      is: [ pageable ]
      queryParameters:
        userId:
          type: integer
          description: ID do usuário para filtrar os pedidos
          example: 12345
      description: Endpoint para listar os pedidos, com suporte a paginação
      responses:
        200:
          body:
            application/json:
              type: response.get.orders
        500:
          description: Erro interno do servidor, tente novamente mais tarde
    post:
      is: [ connection ]
      description: Endpoint para criar um novo pedido
      body:
        application/json:
          type: request.post.orders
      responses:
        201:
          description: Pedido criado com sucesso
        400:
          description: Requisição inválida, verifique os dados enviados
        500:
          description: Erro interno do servidor, tente novamente mais tarde