apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: postgres
  labels:
    app: postgres-core
    role: metrics
spec:
  # O selector deve bater com os labels que o CNPG coloca nos Pods
  selector:
    cnpg.io/cluster: postgres-core
  ports:
  - name: metrics
    port: 9187
    targetPort: 9187
    protocol: TCP
  type: ClusterIP