kafka.brokers=kafka-cluster-kafka-bootstrap.kafka.svc:9092
http.port=8081
items.host=items-sapi.mulesoft.svc.cluster.local
items.protocol=HTTP
items.basePath=api/v{version}
items.port=8081
users.host=users-sapi.mulesoft.svc.cluster.local
users.port=8081
users.basePath=api/v{version}
users.protocol=HTTP