spec:
  containers:
  - name: cloudflared
    image: cloudflare/cloudflared:latest
    args: [
      "tunnel",
      "--no-autoupdate",
      "run",
      "--token",
      "$(TUNNEL_TOKEN)",
      "--url", "http://mule-service:80"
    ]
    env:
    - name: TUNNEL_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-token
          key: token