#%RAML 1.0 DataType
properties: 
  username:
    type: string
    example: "john_doe"
  email:
    type: string
    example: "john.doe@example.com"
  password:
    type: string
    example: "P@ssw0rd!"