#%RAML 1.0
title: Items API
version: v1

traits: 
  secured: !include traits/secured.raml
  pageable: !include traits/pageable.raml

types:
  responses.get.items: !include types/responses/get/items.raml

/{version}:
  /:
    post:
      is: [secured]
      description: Endpoint para criar um novo item
      responses:
        201:
          description: Item criado com sucesso
        400:
          description: Requisição inválida, verifique os dados enviados
        500:
          description: Erro interno do servidor, tente novamente mais tarde
    get:      
      is: [secured, pageable]
      description: Endpoint para listar todos os itens
      responses:
        200:
          description: Lista de itens retornada com sucesso
          body:
            application/json:
              type: responses.get.items
        400:
          description: Requisição inválida, verifique os parâmetros enviados
        500:
          description: Erro interno do servidor, tente novamente mais tarde