monitoring.host=monitoring-sapi.mulesoft.svc.cluster.local
monitoring.port=8081
monitoring.protocol=HTTP
monitoring.basePath=api/v{version}
users.host=users-papi.mulesoft.svc.cluster.local
users.port=8081
users.protocol=HTTP
users.basePath=api/v{version}
items.host=items-papi.mulesoft.svc.cluster.local
items.port=8081
items.protocol=HTTP
items.basePath=api/v{version}
orders.host=orders-papi.mulesoft.svc.cluster.local
orders.port=8081
orders.protocol=HTTP
orders.basePath=api/v{version}