#RAML 1.0 DataType
type: object
properties:
  id:
    type: string
    example: "123e4567-e89b-12d3-a456-426614174000"
  created_at:
    type: string
    example: "2024-06-01T12:00:00Z"
  status:
    type: string
    example: "PENDING"
  total:
    type: number
    example: 59.99
  user_id:
    type: integer
    example: 12345
  order_number:
    type: integer
    example: 1001