#RAML 1.0 Trait
headers:
  Authorization:
    description: Token de autenticação necessário para acessar os endpoints protegidos
    type: string
    example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTYwOTQyMDg0MCwiZXhwIjoxNjA5NDI0NDQwfQ.SflKxwRJSMeKKF2QT4fwpMeJf360n4qvWw"
    required: true