#%RAML 1.0
title: Items API
version: v1

traits: 
  pageable: !include traits/pageable.raml

types: 
  response.get.generate: !include types/responses/get/generate.raml
  responses.get.items: !include types/responses/get/items.raml

/{version}:
  /generate:
    get:
      description: Endpoint para gerar um item de exemplo
      responses:
        200:
          description: Item gerado com sucesso
          body:
            application/json:
              type: response.get.generate
        500:
          description: Erro interno do servidor, tente novamente mais tarde
  /:
    get:
      is: [pageable]
      description: Endpoint para listar todos os itens
      responses:
        200:
          description: Lista de itens retornada com sucesso
          body:
            application/json:
              type: responses.get.items
        400:
          description: Requisição inválida, verifique os parâmetros enviados
        500:
          description: Erro interno do servidor, tente novamente mais tarde