CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY NOT NULL,
    items_value DECIMAL(10, 2),
    user_id integer NOT NULL,
    order_number integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    shipping_fee DECIMAL(10,2) DEFAULT 0.00,
    total DECIMAL(10,2),
    payment_method VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE TABLE IF NOT EXISTS order_items (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id UUID NOT NULL,
    item_id UUID NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT order_items_item_id_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_item_id ON order_items(item_id);

CREATE TABLE IF NOT EXISTS payments (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id UUID NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON payments(order_id);

CREATE TABLE IF NOT EXISTS retry_events (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data JSONB NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    reason VARCHAR(255),
    success BOOLEAN NOT NULL DEFAULT FALSE,
    retries INTEGER NOT NULL DEFAULT 0,
    event_id UUID NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)