#%RAML 1.0
title: Monitoring API
version: v1

types: 
  response.get.health: !include types/responses/get/health.raml

/{version}:
  /health:
    /kafka:
      get:
        description: Endpoint para verificar a saúde do Kafka
        responses:
          200:
            body:
              application/json:
                type: response.get.health
    /postgres:
      get:
        description: Endpoint para verificar a saúde do PostgreSQL
        responses:
          200:
            body:
              application/json:
                type: response.get.health
    /kubernetes:
      get:
        description: Endpoint para verificar a saúde do Kubernetes
        responses:
          200:
            body:
              application/json:
                type: response.get.health