#RAML 1.0 Trait
queryParameters:
  limit:
    description: Número máximo de itens a serem retornados
    type: integer
    example: 10
    required: false
  offset:
    description: Número de itens a serem pulados antes de começar a retornar os resultados
    type: integer
    example: 0
    required: false