http.port=8081
ai.host=generativelanguage.googleapis.com
ai.protocol=HTTPS
ai.basePath=v1beta/models
ai.port=443
db.url=jdbc:postgresql://postgres-core-rw.postgres.svc:5432/mulesoft_db
db.driver=org.postgresql.Driver
kafka.brokers=kafka-cluster-kafka-bootstrap.kafka.svc:9092