#RAML 1.0 Trait
queryParameters:
  page:
    description: Número da página a ser retornada
    type: integer
    example: 1
    required: false
  pageSize:
    description: Quantidade de itens por página
    type: integer
    example: 10
    required: false