#RAML 1.0 DataType
type: object
properties:
  email:
    type: string
    example: "user@example.com"
  username:
    type: string
    example: "user123"
  role:
    type: string
    example: "user"
  id:
    type: integer
    example: 1
