#RAML 1.0 DataType
type: object
properties:
  sku:
    type: string
    example: "ABC123"
  name:
    type: string
    example: "Sample Item"
  description:
    type: string
    example: "This is a sample item description."
  price:
    type: number
    example: 19.99
  image:
    type: string
    example: "https://example.com/images/sample-item.jpg"
  