name: Deploy Kafka Platform

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/kafka/**'
  workflow_dispatch:

jobs:
  infra-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Instalar/Atualizar Strimzi Operator
        run: |
          kubectl create namespace kafka --dry-run=client -o yaml | kubectl apply -f -
          kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kafka Cluster & Exporter
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          # Aplica o cluster (que agora inclui o KafkaExporter)
          kubectl apply -f infra/kafka/cluster/kafka-cluster.yaml

      - name: Deploy Kafka Connect
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          # Aplica o cluster Connect se o arquivo existir
          if [ -f "infra/kafka/cluster/kafka-connect.yaml" ]; then
            kubectl apply -f infra/kafka/cluster/kafka-connect.yaml
          fi

      - name: Provisionar Tópicos
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl apply -f infra/kafka/topics/

      - name: Verificar Status
        run: |
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          kubectl get kafka -n kafka
          kubectl get kafkatopic -n kafka
          kubectl get kafkaconnect -n kafka