CREATE TABLE IF NOT EXISTS public.items (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255),
    sku VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_items_name ON items(name);
CREATE INDEX IF NOT EXISTS idx_items_price ON items(price);
CREATE INDEX IF NOT EXISTS idx_items_sku ON items(sku);

CREATE TABLE IF NOT EXISTS public.stock (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    item_id VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_item_id_fkey FOREIGN KEY (item_id)
        REFERENCES public.items (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

INSERT INTO public.items (id, name, description, price, image, sku, created_at, updated_at) VALUES
('1', 'Item 1', 'Description for Item 1', 10.00, 'https://example.com/image1.jpg', 'SKU001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('2', 'Item 2', 'Description for Item 2', 20.00, 'https://example.com/image2.jpg', 'SKU002', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('3', 'Item 3', 'Description for Item 3', 30.00, 'https://example.com/image3.jpg', 'SKU003', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO public.stock (item_id, quantity) VALUES
('1', 100),
('2', 200),
('3', 300);
